### ISSUE TITLE
换了这款主题页面显示空白

### ISSUE THREAD

**Issue by HongLuDianXue** [lazzzis/hexo-theme-only#1]
你好。
我很喜欢这款主题，但是更换了之后页面是空白的。
在本地hexo s也是空白。而在相同的配置环境下，更换别的主题都是正常的，请问这是出于什么原因呢？
望前辈给予解答。谢谢。

**Comment by lazzzis** [comment]
你好。
我在一架新机子上安装测试了最新版，并没有出现该问题，表现正常。所以我猜测会不会是以下几个问题:

1. 是不是我 [文档](https://github.com/lazzzis/hexo-theme-only/blob/master/docs/README.md) 哪里没有描述清楚？一般在 `npm i lodash.pick highlight.js --save`, `新建 404.md`, `_config.yml.example 更名为 _config.yml` 后一般就可以看到效果了
2. 你说的是不是 `Cannot GET /tags/` 这类问题？这个[文档最后](https://github.com/lazzzis/hexo-theme-only/blob/master/docs/faq.md)有解释，我还没解决，因为某些因素受限于 hexo 本身
3. 如果还是没有解决问题，那么麻烦你看一下浏览器控制台是不是报了什么错？如果有的话，截一下图，或者把报错信息贴一下

---
补充: 刚刚想到会不会是 CDN 链接的关系，因为里面的字体调用的是 google fonts 提供的链接，国内的话可能链接不上。所以刚刚又发布了一个版本，移除了 CDN 链接

**Comment by HongLuDianXue** [comment]
指向“http://localhost:4000/js/manifest.js”的 <script> 加载失败。
指向“http://localhost:4000/js/vendor.js”的 <script> 加载失败。
指向“http://localhost:4000/js/app.js”的 <script> 加载失败。

**Comment by HongLuDianXue** [comment]
我知道问题所在了，我是这样下载主题的
`git clone https://github.com/lazzzis/hexo-theme-only themes/only`
不好意思，之前没有注意到你的下载地址是在这里`https://github.com/lazzzis/hexo-theme-only/releases`
