### ISSUE TITLE
代码高亮

### ISSUE THREAD

**Issue by sphc** [lazzzis/hexo-theme-only#2]
按照指示安装后，发现代码没高亮，请问怎么让代码高亮

**Comment by lazzzis** [comment]
看了你部署的博客，我猜应该是写 markdown 文件时没有指明是哪种语言:

比如
![](https://s7.postimg.org/5b520w0jv/Screen_Shot_2017-11-14_at_10.42.15_AM.png)
会认为是要高亮代码

而这样会认为你不想要高亮代码
![](https://s7.postimg.org/eixahmhwr/Screen_Shot_2017-11-14_at_10.42.47_AM.png)

**Comment by sphc** [comment]
嗯，可以了，请问怎么添加来必力评论系统

**Comment by lazzzis** [comment]
开发的时候没有考虑到`来必力评论系统`，所以默认不支持。但我会试试看增加支持的。

**Comment by lazzzis** [comment]
我在 [v1.2.5](https://github.com/lazzzis/hexo-theme-only/releases/tag/v1.2.5) 中增加了对 `来必力评论系统` 的支持。你可以下载试试看。

**Comment by sphc** [comment]
添加uid后一直卡在这里
![333](https://user-images.githubusercontent.com/26323762/32889465-125155f0-cb06-11e7-9973-1684782064db.PNG)

**Comment by lazzzis** [comment]
1. 目前，我自己博客这边测试是没问题的 [Link](https://lazzzis.github.io/test/post/test)
2. 我看了你的博客，猜测可能是 uid 问题，麻烦再确认一下, 按道理 uid 不会这么短

![](https://s8.postimg.org/zg39dt2ad/Screen_Shot_2017-11-16_at_6.28.20_PM.png)

**Comment by sphc** [comment]
好的，现在可以了，之前是我进错了来必力的网站，所以得到的不是正确的uid，非常感谢
