### ISSUE TITLE
换了这款主题页面显示空白

### ISSUE THREAD

**Issue by HarrySheep** [lazzzis/hexo-theme-only#4]
前辈您好
我下载的是realease里的最新版
效果见https://harrysheep.github.io/

安装都按照文档走的

Console:
(index):9 GET http://localhost:4000/css/ionicons.min.css net::ERR_ABORTED
(index):10 GET http://localhost:4000/css/milligram.min.css net::ERR_ABORTED
(index):11 GET http://localhost:4000/css/comfortaa.css net::ERR_ABORTED
(index):12 GET http://localhost:4000/css/source-sans-pro.css net::ERR_ABORTED
(index):13 GET http://localhost:4000/css/animate.min.css net::ERR_ABORTED
(index):14 GET http://localhost:4000/css/nprogress.css net::ERR_ABORTED
(index):15 GET http://localhost:4000/css/loaders.min.css net::ERR_ABORTED
(index):16 GET http://localhost:4000/css/atom-one-light.css net::ERR_ABORTED
(index):17 GET http://localhost:4000/css/app.css net::ERR_ABORTED
(index):24 GET http://localhost:4000/js/manifest.js net::ERR_ABORTED
(index):25 GET http://localhost:4000/js/vendor.js net::ERR_ABORTED
(index):26 GET http://localhost:4000/js/app.js net::ERR_ABORTED
(index):24 GET http://localhost:4000/js/manifest.js net::ERR_ABORTED
(index):25 GET http://localhost:4000/js/vendor.js net::ERR_ABORTED
(index):26 GET http://localhost:4000/js/app.js net::ERR_ABORTED
favicon.ico:1 GET http://localhost:4000/favicon.ico 404 (Not Found)

请问下这个问题怎么解决呢

**Comment by lazzzis** [comment]
你好，谢谢你的反馈
1. 我在新环境下安装主题，并没有复现该 ISSUE
2. 我看了你仓库的历史提交记录，发现没有看到哪个时间点是使用这个主题的，所以也没法拿你当时的博客内容测试
3. 好像你现在使用的另一个主题是没问题的，这个确实有点奇怪，我也一时间搞不懂是什么原因 （x_x；）
