### ISSUE TITLE
缺少site.json和theme.json

### ISSUE THREAD

**Issue by qq50595531** [lazzzis/hexo-theme-only#6]
我把源码想下载下来，发现有个代理会请求本地3000端号的site.json和theme.json这两个。是否在源码中缺少了服务端这一块的代码。感谢！！！

**Comment by lazzzis** [comment]
是的，因为我在开发时使用的是自己的 blog 的数据。我会在这几天上传一些 fake data 和更新开发文档的。
谢谢反馈

________________________________

**Comment by qq5050595531** [comment]
在页面上找到了对应的格式，感谢关注。

**Comment by lazzzis** [comment]
已更新相关文档和开发用数据
