### ISSUE TITLE
Can I modify 404 page?

### ISSUE THREAD

**Issue by ghost** [lazzzis/hexo-theme-only#8]
After I change my theme, google show 404 page.
It will be fine but I see your 404 page(迷路了么？这里什么也不存在
回到 最开始的地方吧 and Image)
Can I change?

**Comment by lazzzis** [comment]
Unfortunately, for the current version, customizing 404 page is not supported, unless you change and rebuild the source code.

But I don't think it is hard to implement this feature. So I will try to implement it recently and support it in the next version.

**Comment by lazzzis** [comment]
I've implemented this feature. You can download the latest release and follow the instructions on the [documents](https://github.com/lazzzis/hexo-theme-only/blob/master/docs/english/README.md).

If you have any other concerns, feel free to open another new issue to let me know.
